name: backend build

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' ||
            github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        defaults:
            run:
                working-directory: ./backend

        strategy:
            matrix:
                node-version: [16.x, 18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: ./backend/package-lock.json
            - run: npm ci
            - run: npm run build
